"use client";

import { useState } from 'react';
import { Trophy } from 'lucide-react';
import { calculateCRSScore } from '@/lib/utils';
import { jsPDF } from "jspdf";

export default function ImmigrationCalc() {
  const [age, setAge] = useState(25);
  const [education, setEducation] = useState(15);
  const [experience, setExperience] = useState(1);
  const [language, setLanguage] = useState(6);
  const [score, setScore] = useState<number | null>(null);

  const handleCalculate = () => {
    const crsScore = calculateCRSScore(age, education, experience, language);
    setScore(crsScore);
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.text("MyRoute Global - Immigration Report", 20, 20);
    doc.setFontSize(16);
    doc.text(`Target Country: Canada (Express Entry)`, 20, 40);
    doc.text(`Your CRS Score: ${score}`, 20, 60);
    doc.setFontSize(12);
    doc.text(`- Age: ${age}`, 20, 80);
    doc.text(`- Education Points: ${education}`, 20, 90);
    doc.text(`- Experience: ${experience} years`, 20, 100);
    doc.text("------------------------------------------", 20, 110);
    doc.text("Generated by MyRouteGlobal.com 2026", 20, 120);
    doc.save("MyRoute_Immigration_Report.pdf");
  };

  return (
    <div className="bg-primary text-white p-8 rounded-2xl shadow-2xl max-w-3xl mx-auto my-8">
      <h2 className="text-3xl font-bold text-yellow-400 flex items-center gap-3 mb-8">
        <Trophy size={32} /> حاسبة نقاط الهجرة الكندية (CRS)
      </h2>
      <div className="space-y-6">
        <div>
          <label className="block mb-3 font-medium">العمر: {age}</label>
          <input type="range" min="18" max="65" value={age} onChange={(e) => setAge(Number(e.target.value))} className="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer" />
        </div>
        <div>
          <label className="block mb-3 font-medium">التعليم</label>
          <select className="w-full p-3 bg-slate-800 rounded-lg text-white border border-slate-700" onChange={(e) => setEducation(Number(e.target.value))}>
            <option value="5">شهادة ثانوية</option>
            <option value="22">درجة جامعية</option>
            <option value="25">درجة ماجستير</option>
          </select>
        </div>
        <button onClick={handleCalculate} className="w-full bg-yellow-500 text-black font-bold py-4 rounded-xl hover:bg-yellow-600 transition-all text-lg">احسب النقاط الآن</button>
        {score !== null && (
          <div className="mt-8 p-6 bg-slate-800 rounded-xl border-2 border-yellow-400 text-center">
            <div className="text-5xl font-bold text-yellow-400 mb-4">{score}</div>
            <button onClick={downloadPDF} className="mt-4 flex items-center justify-center gap-2 w-full py-2 bg-gray-200 text-gray-800 rounded-lg hover:bg-gray-300 transition-all">تحميل التقرير كـ PDF 📄</button>
          </div>
        )}
      </div>
    </div>
  );
}
